# Generated by Django 3.1.7 on 2021-03-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=30)),
                ('couleur', models.CharField(max_length=30)),
                ('nb_place', models.IntegerField()),
            ],
        ),
    ]
