# Generated by Django 3.1.8 on 2021-06-04 07:58

from django.db import migrations

def create_content_type(apps, schema_editor):
    ContentType = apps.get_model('contenttypes','ContentType')
    ContentType.objects.create(app_label='backend', model='permission')

def create_permissions(apps, schema_editor):
    Permission = apps.get_model('auth','Permission')
    ContentType = apps.get_model('contenttypes','ContentType')

    content = ContentType.objects.get(app_label='backend', model='permission')
    contentUser = ContentType.objects.get(app_label='backend', model='utilisateur')

    Permission.objects.create(name='Accès a la liste des permissions', content_type_id=content.id, codename='permission_list')
    Permission.objects.create(name='Récuperation des informations d\'un permission', content_type_id=content.id, codename='permission_retrieve')

    Permission.objects.create(name='Création d\'un groupe', content_type_id=content.id, codename='groupe_create')
    Permission.objects.create(name='Accès a la liste des groupes', content_type_id=content.id, codename='groupe_list')
    Permission.objects.create(name='Suppression d\'un groupe', content_type_id=content.id, codename='groupe_destroy')
    Permission.objects.create(name='Modification d\'un groupe', content_type_id=content.id, codename='groupe_update')

    
    Permission.objects.create(name='Gestion des permissions', content_type_id=content.id, codename='utilisateur_permission')


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_site_permissions'),
    ]

    operations = [
        migrations.RunPython(create_content_type),
        migrations.RunPython(create_permissions),
    ]
