# Generated by Django 3.1.8 on 2021-06-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_site_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=30)),
                ('couleur', models.CharField(max_length=30)),
                ('nb_place', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vehicules', to='backend.site')),
            ],
        ),
    ]
