# Generated by Django 3.1.8 on 2021-06-20 16:48

from django.db import migrations

def create_content_type(apps, schema_editor):
    ContentType = apps.get_model('contenttypes','ContentType')
    ContentType.objects.create(app_label='backend', model='vehicule')

def create_permissions(apps, schema_editor):
    Permission = apps.get_model('auth','Permission')
    ContentType = apps.get_model('contenttypes','ContentType')

    content = ContentType.objects.get(app_label='backend', model='vehicule')

    Permission.objects.create(name='Création d\'un vehicule', content_type_id=content.id, codename='vehicule_create')
    Permission.objects.create(name='Accès a la liste des vehicules', content_type_id=content.id, codename='vehicule_list')
    Permission.objects.create(name='Suppression d\'un vehicule', content_type_id=content.id, codename='vehicule_destroy')
    Permission.objects.create(name='Archivage d\'un vehicule', content_type_id=content.id, codename='vehicule_archive')
    Permission.objects.create(name='Modification d\'un vehicule', content_type_id=content.id, codename='vehicule_update')
    Permission.objects.create(name='Récuperation des informations d\'un vehicule', content_type_id=content.id, codename='vehicule_retrieve')


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_vehicule'),
    ]

    operations = [
        migrations.RunPython(create_content_type),
        migrations.RunPython(create_permissions),
        
    ]

    