# Generated by Django 3.1.8 on 2021-06-03 09:41

from django.db import migrations

def create_content_type(apps, schema_editor):
    ContentType = apps.get_model('contenttypes','ContentType')
    ContentType.objects.create(app_label='backend', model='emprunt')

def create_permissions(apps, schema_editor):
    Permission = apps.get_model('auth','Permission')
    ContentType = apps.get_model('contenttypes','ContentType')

    content = ContentType.objects.get(app_label='backend', model='emprunt')

    Permission.objects.create(name='Création d\'un emprunt', content_type_id=content.id, codename='emprunt_create')
    Permission.objects.create(name='Accès a la liste des emprunt', content_type_id=content.id, codename='emprunt_list')
    Permission.objects.create(name='Suppression d\'un emprunt', content_type_id=content.id, codename='emprunt_destroy')
    Permission.objects.create(name='Modification d\'un emprunt', content_type_id=content.id, codename='emprunt_update')
    Permission.objects.create(name='Récuperation des informations d\'un emprunt', content_type_id=content.id, codename='emprunt_retrieve')


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_emprunt'),
    ]

    operations = [
        migrations.RunPython(create_content_type),
        migrations.RunPython(create_permissions),
    ]
