# Generated by Django 3.1.8 on 2021-07-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_permissions_permissions'),
        ('backend', '0008_emprunt_permission'),
    ]

    operations = [
    ]
