name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Write django .env
      run: 
        touch ./config/.env &&
        echo "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY" > ./config/.env &&
        echo "DATABASE_URL=$DATABASE_URL" >> ./config/.env
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    - name: Write docker.env
      run: 
        touch ./docker/.env &&
        echo "PORT=$PORT_WEB" > ./docker/.env &&
        echo "PORT_DB=$PORT_DB" >> ./docker/.env
      env:
        PORT_WEB: ${{ secrets.PORT_WEB }}
        PORT_DB: ${{ secrets.PORT_DB }}
    - name: Build the Docker image
      run: docker-compose -f ./docker/docker-compose.yml up --build
