name: Docker & Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
        
        
    steps:
    - uses: actions/checkout@v2
    - name: Write django .env
      run: 
        touch ./config/.env &&
        echo "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY" > ./config/.env &&
        echo "DJANGO_DEBUG=True" >> ./config/.env &&
        echo "DATABASE_URL=$DATABASE_URL" >> ./config/.env
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    - name: Write docker.env
      run: 
        touch ./docker/.env &&
        echo "PORT=$PORT_WEB" > ./docker/.env &&
        echo "PORT_DB=$PORT_DB" >> ./docker/.env
      env:
        PORT_WEB: ${{ secrets.PORT_WEB }}
        PORT_DB: ${{ secrets.PORT_DB }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./docker/web/requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Build the Docker image
      run: docker-compose -f ./docker/docker-compose.yml up -d
